language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before-install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
install:
  - poetry install
script: pytest
