language: python
services:
  - docker
before-install:
  - docker build -t test_build .
  - ID=$(docker run -dit test_build /bin/bash)
install: pip --version
script: docker exec $ID poetry run pytest --cov-report=xml --cov=geok tests/
after_success:
  - docker exec bash codecov.sh -v -f coverage.xml
  - docker kill $ID
deploy:
  provider: script
  script: bash deploy.sh
