language: generic
python:
  # - "3.6" # TODO: builds for 3.6
  - "3.7"
  - "3.8"
before-install:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry shell
install:
  - poetry install -vv
script: pytest
