language: python
services:
  - docker
before-install:
  - docker pull cooksamuel/geok_test:latest
install: pip --version
script: docker run cooksamuel/geok_test:latest /bin/sh -c "poetry run pytest --cov-report=xml --cov=geok tests/"
after_success:
  - bash <(curl -s https://codecov.io/bash)
