language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before-install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
  - POETRY_HOME=/etc/poetry python get-poetry.py
install:
  - /etc/poetry install
script: pytest
