language: python
services:
  - docker
before-install:
  - docker build -t test_build .
  - ID=$(docker run -dit test_build /bin/sh)
install: pip --version
script: docker exec $ID poetry run pytest --cov-report=xml --cov=geok tests/
after_success:
  - docker exec $ID "curl -s https://codecov.io/bash | bash -v -f ./coverage.xml  || echo 'codecov failed to upload'"
  - docker kill $ID
deploy:
  provider: script
  script: bash deploy.sh
